BC_OBJS += src_external/BoundaryConditions/RadialHydraulicPressureBoundaryCondition.o \
	src_external/BoundaryConditions/CavityPressureBoundaryCondition.o \
	src_external/BoundaryConditions/PerforatedCasedWellboreBoundaryCondition.o \
	src_external/BoundaryConditions/Wellbore/PerforatedCasedWellboreProblemInterface.o \
	src_external/BoundaryConditions/Wellbore/PerforatedCasedWellboreProblemInterfaceQA.o \
	src_external/BoundaryConditions/Wellbore/PerforatedCasedWellboreProblemInterfaceQB.o \
	src_external/BoundaryConditions/Wellbore/PerforatedCasedWellboreProblemInterfaceQC.o \
	src_external/BoundaryConditions/Wellbore/PerforatedCasedWellboreProblemInterfaceQD.o


CONTACT_OBJS +=	src_external/Contact/CommonPlaneContact.o \
	src_external/Contact/DESS.o \
	src_external/Contact/NBS.o \
	src_external/Contact/CGRID.o


DATASTRUCTURES_OBJS += 

ELEMENT_OBJS += 

IC_OBJS += 

IO_OBJS += 

LINALG_OBJS += 

MATERIAL_OBJS += src_external/Constitutive/Material/DamageSphericalPores.o \
	src_external/Constitutive/Material/DSIDDamage.o \
	src_external/Constitutive/Interface/JointIntermediate.o \
	src_external/Constitutive/Interface/RateAndStateIntermediate.o \
	src_external/Constitutive/Interface/RateAndState.o \
	src_external/Constitutive/Interface/Dieterich.o \
	src_external/Constitutive/Interface/ItascaJoint.o \
	src_external/Constitutive/Interface/HeuzeJoint.o \
	src_external/Constitutive/Material/LinearElasticOrthotropic.o \
	src_external/Constitutive/Material/LinearElasticGeneralAnisotropic.o

GMM_OBJS += 

MISC_OBJS += src_external/SurfaceGeneration/Fractunator2.o \
	src_external/SurfaceGeneration/Fractunator3.o \
	src_external/SurfaceGeneration/Fractunator2D.o

MPICOMM_OBJS += 

OBJMANAGER_OBJS += src_external/ObjectManagers/FaultElementManagerT.o \
	src_external/ObjectManagers/ChemistryManager.o

SOLVERS_OBJS += src_external/PhysicsSolvers/Hydrofracture/Hydrofracture.o  \
    src_external/PhysicsSolvers/Hydrofracture/TimedPerfectProppant.o  \
	src_external/PhysicsSolvers/FractureFlow/FractureFlowSolver.o \
	src_external/PhysicsSolvers/FractureFlow/MatrixFlowSolver.o \
	src_external/PhysicsSolvers/FractureFlow/FractureFlowSolverExplicit.o \
	src_external/PhysicsSolvers/FractureFlow/ProppantModels.o \
	src_external/PhysicsSolvers/FractureFlow/LeakoffModels.o \
	src_external/PhysicsSolvers/FractureFlow/TwoDADRSolver.o \
	src_external/PhysicsSolvers/FractureFlow/TwoDADRSolver_Proppant.o \
	src_external/PhysicsSolvers/FractureFlow/ParallelPlateProppantFlowSolverImplicit.o \
	src_external/PhysicsSolvers/FractureFlow/ParallelPlateFlowSolverSteadyState.o  \
	src_external/PhysicsSolvers/FractureFlow/LagrangeDynamicsParallelPlateFlowExplicit_Proppant.o \
	src_external/PhysicsSolvers/FractureFlow/ImmiscibleFluidSolverImplicit.o \
	src_external/PhysicsSolvers/FractureFlow/TwoDSteadyStateParallelPlateFlowSolver.o \
	src_external/PhysicsSolvers/Chemistry/FindEquilibriumNew.o \
	src_external/PhysicsSolvers/Chemistry/OneDReactionFront.o \
	src_external/PhysicsSolvers/Chemistry/ReactionFrontMaterialUpdate.o \
	src_external/PhysicsSolvers/Chemistry/QueryChemistryDatabase.o\
	src_external/PhysicsSolvers/Chemistry/OneDReactionFrontApertureUpdate.o \
	src_external/PhysicsSolvers/Seismicity/FaultRuptureDieterich.o \
	src_external/PhysicsSolvers/Seismicity/FaultPropertyVariabilityDieterich.o \
	src_external/PhysicsSolvers/Seismicity/FaultRupture.o \
	src_external/PhysicsSolvers/Seismicity/FaultRuptureBEMSolver.o \
	src_external/PhysicsSolvers/Seismicity/BoundaryElementDataManagerT.o \
	src_external/PhysicsSolvers/Seismicity/SeismicRiskSolver.o \
	src_external/PhysicsSolvers/Seismicity/RiskSites.o \
	src_external/PhysicsSolvers/Seismicity/GroundMotion1D.o \
	src_external/PhysicsSolvers/Seismicity/MicroseismicSourceSolver.o \
	src_external/PhysicsSolvers/Miscellaneous/GroupLabeler.o 



TOTALVIEW_OBJS += 

UTILITIES_OBJS += src_external/Utilities/ChemistryUtilities.o

